---
- name: Configure Network
  hosts: all
  become: yes

  tasks:
  - name: Install Prometheus
    apt:
      name: prometheus
      state: present

  - name: Configure Prometheus
    template:
      src: templates/prometheus.yml.j2
      dest: /etc/prometheus/prometheus.yml
    notify: restart prometheus
